<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductsSeeder extends Seeder
{
    public function run()
    {
        $data = [
            // Áo Thun (category_id: 1)
            [
                'category_id' => 1,
                'name' => 'Áo Thun Basic Trắng',
                'slug' => 'ao-thun-basic-trang',
                'description' => 'Áo thun cotton 100% màu trắng, form regular fit thoải mái',
                'price' => 150000,
                'discount_price' => 120000,
                'stock' => 50,
                'sizes' => 'S,M,L,XL,XXL',
                'colors' => 'Trắng,Đen,Xám',
                'views' => 150,
                'sold_count' => 45,
                'rating_avg' => 4.50,
                'rating_count' => 30,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 1,
                'name' => 'Áo Thun Polo Nam',
                'slug' => 'ao-thun-polo-nam',
                'description' => 'Áo polo nam cao cấp, phong cách lịch lãm',
                'price' => 250000,
                'discount_price' => 200000,
                'stock' => 40,
                'sizes' => 'M,L,XL',
                'colors' => 'Xanh,Đỏ,Đen',
                'views' => 200,
                'sold_count' => 60,
                'rating_avg' => 4.80,
                'rating_count' => 45,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 1,
                'name' => 'Áo Thun Oversize Unisex',
                'slug' => 'ao-thun-oversize-unisex',
                'description' => 'Áo thun form rộng, phong cách streetwear',
                'price' => 180000,
                'discount_price' => null,
                'stock' => 35,
                'sizes' => 'M,L,XL',
                'colors' => 'Đen,Trắng,Xám,Be',
                'views' => 180,
                'sold_count' => 52,
                'rating_avg' => 4.60,
                'rating_count' => 38,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Áo Sơ Mi (category_id: 2)
            [
                'category_id' => 2,
                'name' => 'Áo Sơ Mi Trắng Công Sở',
                'slug' => 'ao-so-mi-trang-cong-so',
                'description' => 'Áo sơ mi trắng form slim, phù hợp công sở',
                'price' => 280000,
                'discount_price' => 250000,
                'stock' => 30,
                'sizes' => 'S,M,L,XL',
                'colors' => 'Trắng',
                'views' => 120,
                'sold_count' => 35,
                'rating_avg' => 4.70,
                'rating_count' => 28,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 2,
                'name' => 'Áo Sơ Mi Kẻ Sọc',
                'slug' => 'ao-so-mi-ke-soc',
                'description' => 'Áo sơ mi kẻ sọc phong cách Hàn Quốc',
                'price' => 320000,
                'discount_price' => null,
                'stock' => 25,
                'sizes' => 'M,L,XL',
                'colors' => 'Xanh,Đen,Xám',
                'views' => 95,
                'sold_count' => 22,
                'rating_avg' => 4.40,
                'rating_count' => 18,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Quần Jean (category_id: 3)
            [
                'category_id' => 3,
                'name' => 'Quần Jean Slim Fit',
                'slug' => 'quan-jean-slim-fit',
                'description' => 'Quần jean ôm form dáng đẹp, co giãn tốt',
                'price' => 450000,
                'discount_price' => 380000,
                'stock' => 45,
                'sizes' => '28,29,30,31,32,33',
                'colors' => 'Xanh đậm,Đen',
                'views' => 250,
                'sold_count' => 78,
                'rating_avg' => 4.90,
                'rating_count' => 65,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 3,
                'name' => 'Quần Jean Baggy Unisex',
                'slug' => 'quan-jean-baggy-unisex',
                'description' => 'Quần jean form rộng, phong cách năng động',
                'price' => 480000,
                'discount_price' => null,
                'stock' => 28,
                'sizes' => '29,30,31,32',
                'colors' => 'Xanh nhạt,Đen',
                'views' => 160,
                'sold_count' => 42,
                'rating_avg' => 4.70,
                'rating_count' => 35,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Quần Kaki (category_id: 4)
            [
                'category_id' => 4,
                'name' => 'Quần Kaki Dài Nam',
                'slug' => 'quan-kaki-dai-nam',
                'description' => 'Quần kaki dài công sở, form chuẩn',
                'price' => 350000,
                'discount_price' => 300000,
                'stock' => 38,
                'sizes' => '28,29,30,31,32',
                'colors' => 'Be,Đen,Xám,Navy',
                'views' => 140,
                'sold_count' => 48,
                'rating_avg' => 4.60,
                'rating_count' => 40,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 4,
                'name' => 'Quần Kaki Short Nam',
                'slug' => 'quan-kaki-short-nam',
                'description' => 'Quần short kaki thoáng mát, năng động',
                'price' => 250000,
                'discount_price' => null,
                'stock' => 42,
                'sizes' => '28,29,30,31,32',
                'colors' => 'Be,Xám,Navy',
                'views' => 110,
                'sold_count' => 38,
                'rating_avg' => 4.50,
                'rating_count' => 32,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Áo Khoác (category_id: 5)
            [
                'category_id' => 5,
                'name' => 'Áo Khoác Hoodie Unisex',
                'slug' => 'ao-khoac-hoodie-unisex',
                'description' => 'Áo hoodie nỉ bông ấm áp, form oversize',
                'price' => 380000,
                'discount_price' => 320000,
                'stock' => 32,
                'sizes' => 'M,L,XL',
                'colors' => 'Đen,Xám,Nâu,Xanh',
                'views' => 220,
                'sold_count' => 65,
                'rating_avg' => 4.80,
                'rating_count' => 55,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 5,
                'name' => 'Áo Khoác Jean Nam',
                'slug' => 'ao-khoac-jean-nam',
                'description' => 'Áo khoác jean phong cách cá tính',
                'price' => 550000,
                'discount_price' => 480000,
                'stock' => 20,
                'sizes' => 'M,L,XL',
                'colors' => 'Xanh,Đen',
                'views' => 185,
                'sold_count' => 38,
                'rating_avg' => 4.70,
                'rating_count' => 30,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 5,
                'name' => 'Áo Khoác Dù Thể Thao',
                'slug' => 'ao-khoac-du-the-thao',
                'description' => 'Áo khoác dù chống nước, phù hợp outdoor',
                'price' => 420000,
                'discount_price' => null,
                'stock' => 4,
                'sizes' => 'L,XL',
                'colors' => 'Đen,Xanh,Đỏ',
                'views' => 95,
                'sold_count' => 28,
                'rating_avg' => 4.50,
                'rating_count' => 22,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Đầm Váy (category_id: 6)
            [
                'category_id' => 6,
                'name' => 'Váy Maxi Hoa Nhí',
                'slug' => 'vay-maxi-hoa-nhi',
                'description' => 'Váy maxi hoa nhí duyên dáng, thoải mái',
                'price' => 380000,
                'discount_price' => 320000,
                'stock' => 25,
                'sizes' => 'S,M,L',
                'colors' => 'Trắng,Xanh,Hồng',
                'views' => 170,
                'sold_count' => 50,
                'rating_avg' => 4.85,
                'rating_count' => 42,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 6,
                'name' => 'Đầm Công Sở Thanh Lịch',
                'slug' => 'dam-cong-so-thanh-lich',
                'description' => 'Đầm công sở phong cách Hàn Quốc',
                'price' => 450000,
                'discount_price' => null,
                'stock' => 30,
                'sizes' => 'S,M,L,XL',
                'colors' => 'Đen,Xanh navy,Be',
                'views' => 135,
                'sold_count' => 40,
                'rating_avg' => 4.75,
                'rating_count' => 35,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'category_id' => 6,
                'name' => 'Váy Jean Ngắn',
                'slug' => 'vay-jean-ngan',
                'description' => 'Váy jean ngắn trẻ trung, năng động',
                'price' => 280000,
                'discount_price' => 250000,
                'stock' => 3,
                'sizes' => 'S,M,L',
                'colors' => 'Xanh,Đen',
                'views' => 125,
                'sold_count' => 45,
                'rating_avg' => 4.65,
                'rating_count' => 38,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('products')->insertBatch($data);
    }
}
